name: Publish to Test PyPI

on:
  push:
    branches:
      - test-stable  # Trigger on test-stable branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Use the latest Python version within the allowed range

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel build twine  # Install necessary tools for building and uploading

    - name: Build distribution
      run: |
        python -m build  # This will create the distribution files (sdist and bdist_wheel)

    - name: Upload to Test PyPI
      run: |
        twine upload --verbose --repository testpypi dist/*  # Upload to Test PyPI for testing
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}  # Use secret for username
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}  # Use secret for password (API token)
